config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :contracts do 
    resources :feedbacks 
  end

  resources :charges

  root 'contracts#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :contracts
end

app/models/contract.rb
class Contract < ApplicationRecord 
  
  mount_uploader :picture, PictureUploader
  belongs_to :user
  belongs_to :category
  has_many :feedbacks
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :contract 
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :contracts
  has_many :feedbacks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
before_action :find_contract, only: [:new, :create]

  def new
  end
  
  def create
    # Amount in cents
    @amount = @contract.price.to_i 
  
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )
  
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'aud'
    )
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
  
  private

  def find_contract
    @contract = Contract.find(params[:contract_id])
  end

end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController

  before_action :find_contract, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category].blank? 
      @contracts = Contract.all.order("created_at DESC")
    else 
      @category_id = Category.find_by(algo: params[:category]).id
      @contracts = Contract.where(category_id: @category_id).order("created_at DESC")
    end
  end 

  def show 
  end 

  def new 
    @contract = current_user.contracts.build
    @categories = Category.all.map {|c| [c.algo, c.id]}
  end 

  def create 
    @contract = current_user.contracts.build(contract_params)
    @contract.category_id = params[:category_id]
    if @contract.save 
      redirect_to root_path 
    else 
      render 'new' 
    end
  end 

  def edit 
    @categories = Category.all.map {|c| [c.algo, c.id]}
  end  

  def update 
    @contract.category_id = params[:category_id]

    if @contract.update(contract_params) 
      redirect_to contract_path(@contract)
    else 
      render 'edit'
    end 
  end 

  def destroy 
    
    @contract.destroy 
    redirect_to root_path 
  end 


  private 

  def contract_params 
    params.require(:contract).permit(:title, :description, :owner, :price, :category_id, :picture, :remove_picture, :picture_cache)
  end
  
  def find_contract
    @contract = Contract.find(params[:id])
  end

end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :find_contract 
  before_action :find_feedback, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

def new 

@feedback = Feedback.new 

end 

def create 
  @feedback = Feedback.new(feedback_params)
  @feedback.contract_id = @contract.id

  @feedback.user_id = current_user.id 

  if @feedback.save 
    redirect_to contract_path(@contract)
  else 
    render 'new'
  end
end 

def edit 
  
end 

def update 
  
  if @feedback.update(feedback_params)
    redirect_to contract_path(@contract)
  else 
    render 'edit'
  end 
end 

def destroy 

  @feedback.destroy 
  redirect_to contract_path(@contract)
end  


private 

def find_contract
  @contract = Contract.find(params[:contract_id])
end 

def feedback_params 
 params.require(:feedback).permit(:rating, :comment)
end 

def find_feedback 
  @feedback = Feedback.find(params[:id])
end 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/charges/create.html.erb
<h2 class="contract-owner">Thanks, you paid <strong>$<%= @contract.price %></strong>!</h2>

<p class="contract-DESC">Redirecting you to our main page......</p>

<script>setTimeout(function(){window.location.href="/"},5000);</script>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= @contract.price %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto">
 </script>
<% end %>

app/views/contracts/_form.html.erb
<%= simple_form_for @contract do |f| %>
         <%= select_tag(:category_id, options_for_select(@categories), prompt: "Select Category") %>
  <%= f.input :title, label: "Contract Title" %>
  <%= f.input :description %>
  <%= f.input :owner %>
  <%= f.input :price %>
  <%= f.label :picture, "Choose Image" %>
  <%= f.file_field :picture %>
  <%= f.button :submit %>
<% end %>

app/views/contracts/edit.html.erb
<h1> Edit Mining Contract Details</h1>
<div class="col-md-10 col-md-offset-1">

 <div class="new-contract-form">

  <% if user_signed_in? && current_user.id == @contract.user_id %>
      <%= simple_form_for(@contract, html: { multipart: true }) do |f| %>
              
        <%= f.select :category_id, @categories %>
        <%= f.input :title, label: "Contract Title" %>
        <%= f.input :description %>
        <%= f.input :owner %>
        <%= f.input :price %>
        <%= f.label :picture, "Choose Image" %>
        <%= f.file_field :picture %>
        <%= f.button :submit %>

   <% else %> 
  <%= redirect_to root_path %>
<% end %>

  <div>
</div>

app/views/contracts/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>
<% if @contracts.count == 0 %>
  <h3>There are no contracts in this category</h3>
<% else %>
  <div class="row">
     <% @contracts.each do |contract| %>
        <div class="col-md-3">
        <% if contract.picture? %>
           <a href="/contracts/ <%= contract.id %>">
           <%= image_tag contract.picture.url, class: "contract" %>
           </a>
        <% end %>
           <h4><%= contract.title %></h4>
           <h4><%= contract.category.algo %></h4>
           <h4>$<%= contract.price %></h4>
           
        </div>
       <% end %>
  </div>
<% end %>

app/views/contracts/new.html.erb
<div class="col-md-10 col-md-offset-1">

      <div class="new-contract-form">
        <h1> New Mining Contract Details</h1>
        <%= render 'form' %>
      <div>
</div>

app/views/contracts/show.html.erb
<div class="row">
       <div class="col-md-4">
       <% if @contract.picture? %>
          <%= image_tag @contract.picture.url, class: "contract-show" %> 
       </div>
       <% end %>

        <div class="col-md-8">

          <div class="contract-info">
              <h2 class="contract-title"><%= @contract.title %></h2>
              <h3 class="contract-owner"><span><em> Please contact:  </em></span><%= @contract.owner %></h3>
              <h4 class="contract-owner"><%= @contract.category.algo %></h4>
              <p class="contract-desc"><%= @contract.description %></p>  
          </div>

          <p class="mt-5">
                            <p class="contract-owner">Price: $<%= @contract.price %></p>
                            <% if user_signed_in? && @contract.user.id != current_user.id %>
                                      <%= form_tag charges_path do %>
                                                <%= hidden_field_tag "contract_id", @contract.id %>

                                                <article>
                                                  <% if flash[:error].present? %>
                                                    <div id="error_explanation">
                                                      <p><%= flash[:error] %></p>
                                                    </div>
                                                  <% end %>
                                                </article>

                                                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                                        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                                                        data-description="<%= @contract.title %>"
                                                        data-amount="<%= (@contract.price) * 100 %>"
                                                        <% if user_signed_in? %>
                                                          data-email="<%= current_user.email %>"
                                                        <% end %>
                                                        data-locale="auto">
                                                </script>
                                      <% end %>
                            <% elsif user_signed_in? && @contract.user.id = current_user.id %>

                                <div class="links btn-group">
                                          <%= link_to "Edit", edit_contract_path(@contract), class: "btn btn-custom" %>
                                          <%= link_to "Delete", contract_path(@contract), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
                                </div>
                                <% else %>
                                <strong class="contract-owner">Please register or login to purchase</strong>
                            <% end %>
                </p>
        </div>
</div>

<div class="row">
  <div class="col-md-12">
  
     <div class="feedbacks">
       <h1> Feedbacks </h1>
        <% if @contract.feedbacks.count == 0 %>
           <em class="contract-owner">There is no feedbacks so far</em>
        <% else %>
           <%= render @contract.feedbacks %>
        <% end %>
     </div>
    <div>
    </div>
    </br>
    </br>
    <div class="row">
            <% if user_signed_in? %>
               <% if @contract.user_id != current_user.id %>
                  <%= link_to "Add Feedbacks", new_contract_feedback_path(@contract), class: "btn-custom"%>
               <% end %>
            <% end %>
    </div>
  </div>

  </br>
  </br>
  </br>
  </br>

app/views/feedbacks/_feedback.html.erb
<div class='feedback'> 
  <p><%= feedback.rating %>
  <p class="feedback-comment">
     <%= feedback.comment %>
  </p>
  <% if user_signed_in? %>
  
      <% if feedback.user_id == current_user.id %>

         <div class="links btn-group">
            <%= link_to "Change Feedback", edit_contract_feedback_path(feedback.contract, feedback), class: "btn btn-custom" %>
            <%= link_to "Delete Feedback", contract_feedback_path(feedback.contract, feedback), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
         </div>
         <% end %>
  <% end %>

  </div>

app/views/feedbacks/_form.html.erb
<%= simple_form_for([@contract, @contract.feedbacks.build]) do |f| %>
  <div id="rating-form">
     <%= f.input :rating %>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit, class: "btn-custom2" %>

<% end %>

app/views/feedbacks/edit.html.erb
<div class="col-md-10 col-md-offset-1">
   <div class="edit-feedback-form">

   <h1> Change My Feedback </h1>>

    <%= simple_form_for([@contract, @feedback]) do |f| %>
      <div id="rating-form">
          <%= f.input :rating %>
      </div>
      <%= f.input :comment %>
      <%= f.button :submit, class: "btn-custom2" %>

    <% end %>
 </div>
</div>

app/views/feedbacks/new.html.erb
<div class="col-md-10 col-md-offset-1">

   <div class="new-feedback-form">

      <h1> Customer Feedback </h1>

         <%= render 'form' %>
   </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minerexchange</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <nav class="navbar navbar-default"> 
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Miner Exchange", root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav">
        <li class="dropdown"> 
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Sort By Algorithm   <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
             <% Category.all.each do |category| %>
               <li class="<%= 'active' if params[:category] == category.algo %>">
               <%= link_to category.algo, contracts_path(category: category.algo), class: "link" %>
               </li>
             <% end %>
          </ul>
        </li>

        <% if user_signed_in? %>
          <li><%= link_to "Create Your Contract", new_contract_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
   
    <%= yield %>
  </body>
</html>